# ~/.config/hypr/hyprlock.conf

# -----------------
# ARKA PLAN (SADECE WALLPAPER)
# -----------------
background {
    monitor = 
    # **Kendi görsel dosyanızın TAM YOLUNU buraya girin.** 
    path = ~/hyprlandproject/pictures/hyprlock_pictures/lock.png 
    
    # Bulanıklığı tamamen devre dışı bırakır (İstenen basitlik için)
    blur_passes = 0 
    
    # Görsel yüklenirken gösterilecek yedek renk (isteğe bağlı)
    color = rgba(25, 20, 20, 1.0) 
}

# ~/.config/hypr/hyprlock.conf devamı

# -----------------
# GİRİŞ ALANI (ŞİFRE MENÜSÜ)
# -----------------
input-field {
    size = 250, 60 # Giriş alanının boyutu
    rounding = -1 # Tamamen yuvarlak kenarlar için (oval)
    dots_color = white # Şifre noktalarının rengi
    font_color = rgb(255,255,255) # Yazı rengi
    fade_on_empty = true # Giriş yapılmadığında soluklaşsın
    position = 0, -200 # Ekranın merkezinden 200 piksel yukarıda konumlandırır
    halign = center 
    valign = center
}

# ~/.config/hypr/hyprlock.conf devamı

# -----------------
# İKON (STATİK GÖRSEL)
# -----------------
image {
    monitor = 
    path = /home/emir/Pictures/Wallpapers/lock.png
    size = 150 
    rounding = -1 
    position = 0, 200 
    halign = center 
    valign = center
}


# -----------------
# ETİKET: ANLIK SAAT
# -----------------
label {
    monitor = 
    text = $TIME 
    color = rgba(255, 255, 255, 1.0)
    font_size = 80
    font_family = FiraCode Nerd Font
    position = 0, -50
    halign = center 
    valign = center
}


# -----------------
# ETİKET: GÜN VE TARİH
# -----------------
label {
    monitor = 
    # Her 1000 ms'de (1 saniyede) kabuk komutunu çalıştırır
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 22
    font_family = Noto Sans
    position = 0, 50
    halign = center 
    valign = center
}

# -----------------
# ETİKET: SABİT MESAJ / ALINTI
# -----------------
label {
    monitor =
    text = MehmetEmirKeles | Hyprland / Arch Linux
    color = rgba(250, 250, 250, 1.0) 
    font_size = 25
    font_family = FiraCode Nerd Font
    position = 0, -300 
    halign = center
    valign = center
}
